#!/usr/bin/env bash
#
# run-tests.sh — Tests for Vault PKI node certificate issuance and renewal
#
# Usage:
#   ./tests/pki/run-tests.sh
#
# Runs in a few seconds. No cluster, no cloud account, no credentials.
#
# scripts/issue-node-cert.sh rewrites the TLS material of a running Vault
# node and then signals it to reload. Every interesting failure here ends
# with a node that cannot serve TLS, which on the active node is an
# outage — so the cases below are mostly about what it must refuse to do.
#
# Certificates are generated by make-fixtures.sh rather than committed:
# a throwaway private key in git is still a private key in git, and these
# need specific expiry dates anyway.
#
# Requirements: bash, jq, openssl

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
ISSUE="${REPO_ROOT}/scripts/issue-node-cert.sh"
BOOTSTRAP="${REPO_ROOT}/scripts/bootstrap-pki.sh"
FAKE_BIN="${SCRIPT_DIR}/fake-bin"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

export FIXTURES="${WORK}/fixtures"

PASS=0
FAIL=0
SKIP=0

green() { printf '\033[32m%s\033[0m\n' "$*"; }
red()   { printf '\033[31m%s\033[0m\n' "$*"; }

ok()   { PASS=$((PASS + 1)); green "  PASS  $1"; }
skip() { SKIP=$((SKIP + 1)); printf '  SKIP  %s\n' "$1"; [[ -n "${2:-}" ]] && printf '        %s\n' "$2"; return 0; }
bad() { FAIL=$((FAIL + 1)); red   "  FAIL  $1"; [[ -n "${2:-}" ]] && printf '        %s\n' "$2"; return 0; }

CN="vault-0.vault.internal"

# ---------------------------------------------------------------------------
# Harness
# ---------------------------------------------------------------------------
RC=0
OUT=""
LOG=""
TLS_DIR=""

# Scenario variables must be exported: the shims are grandchildren of this
# shell, so a `VAR=x run_issue` prefix would not reach them.
reset_scenario() {
    export FAKE_ISSUE_RC=0
    export FAKE_ISSUE_MODE=good
    export FAKE_APPROLE_RC=0
    export FAKE_RELOAD_RC=0
    export FAKE_GENERIC_RC=0
    export VAULT_ADDR=https://127.0.0.1:8200
    export VAULT_TOKEN=s.testtoken
    unset VAULT_ROLE_ID VAULT_SECRET_ID 2>/dev/null || true

    TLS_DIR="${WORK}/tls.$RANDOM"
    mkdir -p "$TLS_DIR"
}

# install_existing <fixture>  — put a certificate on the "node" already
install_existing() {
    cp "${FIXTURES}/$1.crt" "${TLS_DIR}/vault.crt"
    cp "${FIXTURES}/$1.key" "${TLS_DIR}/vault.key"
    cp "${FIXTURES}/ca.crt" "${TLS_DIR}/ca.crt"
}

run_issue() {
    local logfile="${WORK}/calls.$$.log"
    : > "$logfile"
    RC=0
    OUT="$(FAKE_LOG="$logfile" PATH="${FAKE_BIN}:${PATH}" \
        "$ISSUE" --tls-dir "$TLS_DIR" --common-name "$CN" "$@" 2>&1)" || RC=$?
    LOG="$(cat "$logfile")"
}

assert_rc()        { if [[ "$RC" == "$2" ]]; then ok "$1"; else bad "$1" "expected exit ${2}, got ${RC}: ${OUT}"; fi; }
assert_says()      { if [[ "$OUT" == *"$2"* ]]; then ok "$1"; else bad "$1" "output lacked: ${2}"; fi; }
assert_log_has()   { if [[ "$LOG" == *"$2"* ]]; then ok "$1"; else bad "$1" "no call matching: ${2}"; fi; }
assert_log_lacks() { if [[ "$LOG" != *"$2"* ]]; then ok "$1"; else bad "$1" "unexpected call: ${2}"; fi; }

# assert_unchanged <label> <file> <expected-sha>
assert_unchanged() {
    local got
    got="$(sha256sum "$2" 2>/dev/null | cut -d' ' -f1)"
    if [[ "$got" == "$3" ]]; then ok "$1"; else bad "$1" "$(basename "$2") was modified"; fi
}

sha_of() { sha256sum "$1" 2>/dev/null | cut -d' ' -f1; }

# ---------------------------------------------------------------------------
# Preflight
# ---------------------------------------------------------------------------
for dep in jq openssl; do
    command -v "$dep" >/dev/null 2>&1 || { red "ERROR: ${dep} not found on PATH"; exit 1; }
done
[[ -x "$ISSUE" ]]     || { red "ERROR: ${ISSUE} is not executable"; exit 1; }
[[ -x "$BOOTSTRAP" ]] || { red "ERROR: ${BOOTSTRAP} is not executable"; exit 1; }

"${SCRIPT_DIR}/make-fixtures.sh" "$FIXTURES" >/dev/null 2>&1 \
    || { red "ERROR: could not generate fixtures"; exit 1; }

# Windows filesystems ignore chmod, so the mode assertion later cannot
# hold there. Probe rather than assume: a silent pass would be a test
# reporting green while checking nothing, and on Linux CI this must run.
PERMS_SUPPORTED=false
probe="${WORK}/probe"; : > "$probe"; chmod 600 "$probe" 2>/dev/null || true
[[ "$(stat -c '%a' "$probe" 2>/dev/null)" == "600" ]] && PERMS_SUPPORTED=true
rm -f "$probe"

# If the shims are not resolved first, every assertion below is meaningless.
if PATH="${FAKE_BIN}:${PATH}" command -v vault | grep -q "fake-bin"; then
    ok "the vault shim shadows any real vault on PATH"
else
    red "ERROR: fake-bin is not being resolved first"; exit 1
fi

# The fixtures must have the properties the tests depend on, or the tests
# pass for the wrong reason.
reset_scenario
if openssl x509 -in "${FIXTURES}/fresh.crt" -noout -checkend 86400 >/dev/null 2>&1; then
    ok "the 'fresh' fixture is valid beyond the renewal window"
else
    bad "the 'fresh' fixture is valid beyond the renewal window"
fi
if openssl x509 -in "${FIXTURES}/expiring.crt" -noout -checkend 86400 >/dev/null 2>&1; then
    bad "the 'expiring' fixture expires inside the renewal window"
else
    ok "the 'expiring' fixture expires inside the renewal window"
fi

# The hostname check keys off openssl's *output*, because `x509
# -checkhost` exits 1 on a mismatch in OpenSSL 3.5 and exits 0 in the 3.0
# Ubuntu ships. Relying on the exit code accepted any certificate on
# exactly the distribution the nodes run.
#
# That makes the wording load-bearing, so pin it here: if a future
# OpenSSL rephrases this, the failure lands on this line rather than
# turning every certificate into an accepted one.
MATCH_OUT="$(openssl x509 -in "${FIXTURES}/good.crt" -noout -checkhost "$CN" 2>&1 || true)"
MISMATCH_OUT="$(openssl x509 -in "${FIXTURES}/wronghost.crt" -noout -checkhost "$CN" 2>&1 || true)"

if [[ "$MATCH_OUT" == *"does match"* && "$MATCH_OUT" != *"NOT match"* ]]; then
    ok "openssl still says 'does match' for a matching certificate"
else
    bad "openssl still says 'does match' for a matching certificate" "got: ${MATCH_OUT}"
fi
if [[ "$MISMATCH_OUT" == *"NOT match"* ]]; then
    ok "openssl still says 'NOT match' for a mismatched certificate"
else
    bad "openssl still says 'NOT match' for a mismatched certificate" "got: ${MISMATCH_OUT}"
fi

# ---------------------------------------------------------------------------
printf '\n=== Argument handling ===\n'
# ---------------------------------------------------------------------------
reset_scenario
RC=0; OUT="$(PATH="${FAKE_BIN}:${PATH}" "$ISSUE" --tls-dir "$TLS_DIR" 2>&1)" || RC=$?
if [[ $RC -ne 0 && "$OUT" == *"--common-name is required"* ]]; then
    ok "rejects a missing --common-name"
else
    bad "rejects a missing --common-name" "got ${RC}: ${OUT}"
fi

reset_scenario
run_issue --wat
assert_says "rejects unknown arguments" "Unknown argument"

# ---------------------------------------------------------------------------
printf '\n=== Renewal is a no-op until it needs to happen ===\n'
# ---------------------------------------------------------------------------
# A daily timer on three nodes that reissued every run would churn
# certificates constantly and SIGHUP the cluster for no reason.
reset_scenario
install_existing fresh
before="$(sha_of "${TLS_DIR}/vault.crt")"
run_issue --renew-within 1
assert_rc        "a fresh certificate means no work" 0
assert_log_lacks "no certificate is issued"          "/issue/"
assert_log_lacks "Vault is not signalled"            "systemctl"
assert_unchanged "the certificate on disk is untouched" "${TLS_DIR}/vault.crt" "$before"
assert_says      "and it says why"                   "nothing to do"

# The no-op path must not even authenticate — an hourly login per node
# for a no-op is pure token churn.
assert_log_lacks "it does not log in for a no-op" "approle/login"

reset_scenario
install_existing expiring
run_issue --renew-within 1
assert_rc      "a nearly expired certificate is renewed" 0
assert_log_has "a new certificate is issued"             "/issue/"

reset_scenario
install_existing fresh
run_issue --renew-within 1 --force
assert_rc      "--force renews regardless" 0
assert_log_has "and issues"                "/issue/"

# No certificate at all is the first-issue case, not an error.
reset_scenario
run_issue --renew-within 1
assert_rc      "a missing certificate is issued" 0
assert_log_has "and it issues one"               "/issue/"

# ---------------------------------------------------------------------------
printf '\n=== A bad certificate is never installed ===\n'
# ---------------------------------------------------------------------------
# Installing a mismatched pair and signalling Vault takes the listener
# down. On the active node that is an outage, caused by the thing meant
# to prevent one.
reset_scenario
install_existing fresh
before_crt="$(sha_of "${TLS_DIR}/vault.crt")"
before_key="$(sha_of "${TLS_DIR}/vault.key")"
export FAKE_ISSUE_MODE=mismatch
run_issue --force
assert_rc        "a mismatched cert/key pair aborts"  1
assert_says      "and says so"                        "do not match"
assert_unchanged "the old certificate survives"       "${TLS_DIR}/vault.crt" "$before_crt"
assert_unchanged "the old key survives"               "${TLS_DIR}/vault.key" "$before_key"
assert_log_lacks "Vault is not signalled"             "systemctl"

# A certificate for the wrong host installs cleanly and is then rejected
# by peers during the Raft join, with an error that reads like a network
# problem. Catch it here instead.
reset_scenario
install_existing fresh
before_crt="$(sha_of "${TLS_DIR}/vault.crt")"
export FAKE_ISSUE_MODE=wronghost
run_issue --force
assert_rc        "a certificate for another host aborts" 1
assert_says      "and names the host it wanted"          "$CN"
assert_unchanged "the old certificate survives"          "${TLS_DIR}/vault.crt" "$before_crt"
assert_log_lacks "Vault is not signalled"                "systemctl"

reset_scenario
install_existing fresh
before_crt="$(sha_of "${TLS_DIR}/vault.crt")"
export FAKE_ISSUE_MODE=empty
run_issue --force
assert_rc        "an empty certificate aborts"  1
assert_unchanged "the old certificate survives" "${TLS_DIR}/vault.crt" "$before_crt"

reset_scenario
export FAKE_ISSUE_MODE=nokey
run_issue --force
assert_rc   "a response with no private key aborts" 1
assert_says "and says what was missing"             "no certificate or no private key"

reset_scenario
export FAKE_ISSUE_MODE=notpem
run_issue --force
assert_rc "a non-PEM certificate aborts" 1

reset_scenario
install_existing fresh
before_crt="$(sha_of "${TLS_DIR}/vault.crt")"
export FAKE_ISSUE_RC=2
run_issue --force
assert_rc        "a refused issuance aborts"    1
assert_says      "and points at the likely cause" "allowed_domains"
assert_unchanged "the old certificate survives" "${TLS_DIR}/vault.crt" "$before_crt"

# ---------------------------------------------------------------------------
printf '\n=== The happy path installs and reloads ===\n'
# ---------------------------------------------------------------------------
reset_scenario
run_issue --force
assert_rc      "issuance succeeds" 0
if [[ -s "${TLS_DIR}/vault.crt" && -s "${TLS_DIR}/vault.key" && -s "${TLS_DIR}/ca.crt" ]]; then
    ok "certificate, key and CA are all written"
else
    bad "certificate, key and CA are all written"
fi

# The installed pair has to match, or the node stops serving.
cm="$(openssl x509 -noout -modulus -in "${TLS_DIR}/vault.crt" 2>/dev/null | openssl md5)"
km="$(openssl rsa -noout -modulus -in "${TLS_DIR}/vault.key" 2>/dev/null | openssl md5)"
if [[ -n "$cm" && "$cm" == "$km" ]]; then
    ok "the installed certificate and key match"
else
    bad "the installed certificate and key match"
fi

# The private key must not be world-readable. It is the one file here
# that grants the ability to impersonate this node.
if [[ "$PERMS_SUPPORTED" == true ]]; then
    PERM="$(stat -c '%a' "${TLS_DIR}/vault.key" 2>/dev/null || echo "unknown")"
    if [[ "$PERM" == "600" ]]; then
        ok "the private key is mode 0600"
    else
        bad "the private key is mode 0600" "got ${PERM}"
    fi
else
    skip "the private key is mode 0600" "this filesystem ignores chmod; runs in CI"
fi

assert_log_has "Vault is signalled to reload" "systemctl reload vault"

# Reload, not restart. A restart on the active node drops leadership and,
# without auto-unseal, needs a manual unseal to come back.
assert_log_lacks "it does not restart Vault" "restart vault"

reset_scenario
run_issue --force --no-reload
assert_rc        "--no-reload still installs" 0
assert_log_lacks "and does not signal"        "systemctl"
assert_says      "but warns the old cert is still live" "until reloaded"

# A failed reload is an error: the files on disk no longer match what the
# running process is serving, and nothing else will notice.
reset_scenario
export FAKE_RELOAD_RC=1
run_issue --force
assert_rc   "a failed reload is an error" 1
assert_says "and says what that means"    "still serving the previous certificate"

# ---------------------------------------------------------------------------
printf '\n=== Authentication ===\n'
# ---------------------------------------------------------------------------
reset_scenario
unset VAULT_TOKEN
run_issue --force
assert_rc   "no credentials is an error" 1
assert_says "and names what is missing"  "VAULT_ROLE_ID"

reset_scenario
unset VAULT_TOKEN
export VAULT_ROLE_ID=role VAULT_SECRET_ID=secret
run_issue --force
assert_rc      "AppRole is used when no token is set" 0
assert_log_has "it logs in"                           "approle/login"
assert_log_has "and revokes the token it minted"      "token revoke"

reset_scenario
unset VAULT_TOKEN
export VAULT_ROLE_ID=role VAULT_SECRET_ID=secret FAKE_APPROLE_RC=2
run_issue --force
assert_rc        "a failed login aborts"   1
assert_log_lacks "and issues nothing"      "/issue/"

# A token the caller supplied belongs to the caller.
reset_scenario
run_issue --force
assert_log_lacks "a supplied VAULT_TOKEN is not revoked" "token revoke"

# ---------------------------------------------------------------------------
printf '\n=== bootstrap-pki.sh ===\n'
# ---------------------------------------------------------------------------
reset_scenario
RC=0
OUT="$(FAKE_LOG="${WORK}/bootstrap.log" PATH="${FAKE_BIN}:${PATH}" \
    VAULT_ADDR='' VAULT_TOKEN=t "$BOOTSTRAP" 2>&1)" || RC=$?
if [[ $RC -ne 0 && "$OUT" == *"VAULT_ADDR"* ]]; then
    ok "bootstrap requires VAULT_ADDR"
else
    bad "bootstrap requires VAULT_ADDR" "got ${RC}: ${OUT}"
fi

RC=0
OUT="$(FAKE_LOG="${WORK}/bootstrap.log" PATH="${FAKE_BIN}:${PATH}" \
    VAULT_ADDR=https://x VAULT_TOKEN='' "$BOOTSTRAP" 2>&1)" || RC=$?
if [[ $RC -ne 0 && "$OUT" == *"VAULT_TOKEN"* ]]; then
    ok "bootstrap requires VAULT_TOKEN"
else
    bad "bootstrap requires VAULT_TOKEN" "got ${RC}: ${OUT}"
fi

# The PKI role must permit client auth as well as server auth. Raft peers
# authenticate in both directions, so a server-only role produces a
# cluster that serves clients and cannot form quorum.
BOOTSTRAP_TEXT="$(cat "$BOOTSTRAP")"
if [[ "$BOOTSTRAP_TEXT" == *"client_flag=true"* ]]; then
    ok "the node role allows client auth (Raft peers need it)"
else
    bad "the node role allows client auth (Raft peers need it)"
fi
if [[ "$BOOTSTRAP_TEXT" == *"allow_ip_sans=true"* ]]; then
    ok "the node role allows IP SANs (peers dial by address)"
else
    bad "the node role allows IP SANs (peers dial by address)"
fi

# The issuing policy must not grant more than issuance. A node that can
# rewrite the role can mint a certificate for any domain.
for forbidden in 'path "pki/root' 'sys/mounts' 'pki/roles'; do
    if [[ "$BOOTSTRAP_TEXT" == *"${forbidden}\""* ]]; then
        bad "the issuing policy does not grant ${forbidden}"
    else
        ok "the issuing policy does not grant ${forbidden}"
    fi
done

# ---------------------------------------------------------------------------
printf '\n=== The role does not overclaim ===\n'
# ---------------------------------------------------------------------------
# Vault PKI cannot issue the certificate the cluster needs in order to
# start. Every doc and default here has to say so, or someone will enable
# this expecting it to replace the bootstrap CA and find out during a
# rebuild that it does not.
DEFAULTS="${REPO_ROOT}/ansible/roles/vault_pki/defaults/main.yml"
TASKS="${REPO_ROOT}/ansible/roles/vault_pki/tasks/main.yml"

ENABLED="$(grep -E '^vault_pki_enabled:' "$DEFAULTS" | awk '{print $2}')"
if [[ "$ENABLED" == "false" ]]; then
    ok "the role is off by default"
else
    bad "the role is off by default" "got '${ENABLED}'"
fi

if grep -qi 'bootstrap' "$DEFAULTS" && grep -qi 'bootstrap' "$TASKS"; then
    ok "the role documents the bootstrap dependency"
else
    bad "the role documents the bootstrap dependency"
fi

# Renewing when there is nothing to renew means the bootstrap step was
# skipped. That has to fail loudly, not produce a timer that fails nightly.
if grep -q 'does not exist' "$TASKS"; then
    ok "the role fails clearly when there is no bootstrap certificate"
else
    bad "the role fails clearly when there is no bootstrap certificate"
fi

SERVICE="${REPO_ROOT}/ansible/roles/vault_pki/templates/vault-cert-renew.service.j2"
SERVICE_TEXT="$(cat "$SERVICE")"
if [[ "$SERVICE_TEXT" == *"EnvironmentFile="* ]]; then
    ok "credentials come from an EnvironmentFile, not the command line"
else
    bad "credentials come from an EnvironmentFile, not the command line"
fi
if [[ "$SERVICE_TEXT" != *"SECRET_ID="* && "$SERVICE_TEXT" != *"VAULT_TOKEN="* ]]; then
    ok "no credential is baked into the unit file"
else
    bad "no credential is baked into the unit file"
fi

# ---------------------------------------------------------------------------
printf '\n=== Results ===\n'
# ---------------------------------------------------------------------------
printf 'passed: %d\nfailed: %d\nskipped: %d\n' "$PASS" "$FAIL" "$SKIP"
if [[ $FAIL -gt 0 ]]; then
    red "FAILED"
    exit 1
fi
green "All ${PASS} assertions passed."
