#!/usr/bin/env bash
#
# run-tests.sh — Tests for Vault PKI node certificate issuance and renewal
#
# Usage:
#   ./tests/pki/run-tests.sh
#
# Runs in a few seconds. No cluster, no cloud account, no credentials.
#
# scripts/issue-node-cert.sh rewrites the TLS material of a running Vault
# node and then signals it to reload. Every interesting failure here ends
# with a node that cannot serve TLS, which on the active node is an
# outage — so the cases below are mostly about what it must refuse to do.
#
# Certificates are generated by make-fixtures.sh rather than committed:
# a throwaway private key in git is still a private key in git, and these
# need specific expiry dates anyway.
#
# Requirements: bash, jq, openssl

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
ISSUE="${REPO_ROOT}/scripts/issue-node-cert.sh"
BOOTSTRAP="${REPO_ROOT}/scripts/bootstrap-pki.sh"
FAKE_BIN="${SCRIPT_DIR}/fake-bin"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

export FIXTURES="${WORK}/fixtures"

PASS=0
FAIL=0
SKIP=0

green() { printf '\033[32m%s\033[0m\n' "$*"; }
red()   { printf '\033[31m%s\033[0m\n' "$*"; }

ok()   { PASS=$((PASS + 1)); green "  PASS  $1"; }
skip() { SKIP=$((SKIP + 1)); printf '  SKIP  %s\n' "$1"; [[ -n "${2:-}" ]] && printf '        %s\n' "$2"; return 0; }
bad() { FAIL=$((FAIL + 1)); red   "  FAIL  $1"; [[ -n "${2:-}" ]] && printf '        %s\n' "$2"; return 0; }

CN="vault-0.vault.internal"

# ---------------------------------------------------------------------------
# Harness
# ---------------------------------------------------------------------------
RC=0
OUT=""
LOG=""
TLS_DIR=""

# Scenario variables must be exported: the shims are grandchildren of this
# shell, so a `VAR=x run_issue` prefix would not reach them.
reset_scenario() {
    export FAKE_ISSUE_RC=0
    export FAKE_ISSUE_MODE=good
    export FAKE_APPROLE_RC=0
    export FAKE_RELOAD_RC=0
    export FAKE_GENERIC_RC=0
    export VAULT_ADDR=https://127.0.0.1:8200
    export VAULT_TOKEN=s.testtoken
    unset VAULT_ROLE_ID VAULT_SECRET_ID 2>/dev/null || true

    # mktemp, not $RANDOM -- see the note in tests/agent. Certificates
    # left by one scenario would be read as another's.
    TLS_DIR="$(mktemp -d "${WORK}/tls.XXXXXXXX")"
    mkdir -p "$TLS_DIR"
}

# install_existing <fixture>  — put a certificate on the "node" already
install_existing() {
    cp "${FIXTURES}/$1.crt" "${TLS_DIR}/vault.crt"
    cp "${FIXTURES}/$1.key" "${TLS_DIR}/vault.key"
    cp "${FIXTURES}/ca.crt" "${TLS_DIR}/ca.crt"
}

run_issue() {
    local logfile="${WORK}/calls.$$.log"
    : > "$logfile"
    RC=0
    # --no-verify-reload throughout: confirming the reload means opening a
    # TLS connection to a listener and reading the certificate back, which
    # a shim cannot provide. That check is proven in tests/integration
    # against a real Vault instead — it is exactly the class of thing
    # shims cannot reach.
    OUT="$(FAKE_LOG="$logfile" PATH="${FAKE_BIN}:${PATH}" \
        "$ISSUE" --tls-dir "$TLS_DIR" --common-name "$CN" --no-verify-reload "$@" 2>&1)" || RC=$?
    LOG="$(cat "$logfile")"
}

assert_rc()        { if [[ "$RC" == "$2" ]]; then ok "$1"; else bad "$1" "expected exit ${2}, got ${RC}: ${OUT}"; fi; }
assert_says()      { if [[ "$OUT" == *"$2"* ]]; then ok "$1"; else bad "$1" "output lacked: ${2}"; fi; }
assert_log_has()   { if [[ "$LOG" == *"$2"* ]]; then ok "$1"; else bad "$1" "no call matching: ${2}"; fi; }
assert_log_lacks() { if [[ "$LOG" != *"$2"* ]]; then ok "$1"; else bad "$1" "unexpected call: ${2}"; fi; }

# assert_unchanged <label> <file> <expected-sha>
assert_unchanged() {
    local got
    got="$(sha256sum "$2" 2>/dev/null | cut -d' ' -f1)"
    if [[ "$got" == "$3" ]]; then ok "$1"; else bad "$1" "$(basename "$2") was modified"; fi
}

sha_of() { sha256sum "$1" 2>/dev/null | cut -d' ' -f1; }

# ---------------------------------------------------------------------------
# Preflight
# ---------------------------------------------------------------------------
for dep in jq openssl; do
    command -v "$dep" >/dev/null 2>&1 || { red "ERROR: ${dep} not found on PATH"; exit 1; }
done
[[ -x "$ISSUE" ]]     || { red "ERROR: ${ISSUE} is not executable"; exit 1; }
[[ -x "$BOOTSTRAP" ]] || { red "ERROR: ${BOOTSTRAP} is not executable"; exit 1; }

"${SCRIPT_DIR}/make-fixtures.sh" "$FIXTURES" >/dev/null 2>&1 \
    || { red "ERROR: could not generate fixtures"; exit 1; }

# Windows filesystems ignore chmod, so the mode assertion later cannot
# hold there. Probe rather than assume: a silent pass would be a test
# reporting green while checking nothing, and on Linux CI this must run.
PERMS_SUPPORTED=false
probe="${WORK}/probe"; : > "$probe"; chmod 600 "$probe" 2>/dev/null || true
[[ "$(stat -c '%a' "$probe" 2>/dev/null)" == "600" ]] && PERMS_SUPPORTED=true
rm -f "$probe"

# If the shims are not resolved first, every assertion below is meaningless.
if PATH="${FAKE_BIN}:${PATH}" command -v vault | grep -q "fake-bin"; then
    ok "the vault shim shadows any real vault on PATH"
else
    red "ERROR: fake-bin is not being resolved first"; exit 1
fi

# The fixtures must have the properties the tests depend on, or the tests
# pass for the wrong reason.
reset_scenario
if openssl x509 -in "${FIXTURES}/fresh.crt" -noout -checkend 86400 >/dev/null 2>&1; then
    ok "the 'fresh' fixture is valid beyond the renewal window"
else
    bad "the 'fresh' fixture is valid beyond the renewal window"
fi
if openssl x509 -in "${FIXTURES}/expiring.crt" -noout -checkend 86400 >/dev/null 2>&1; then
    bad "the 'expiring' fixture expires inside the renewal window"
else
    ok "the 'expiring' fixture expires inside the renewal window"
fi

# The hostname check keys off openssl's *output*, because `x509
# -checkhost` exits 1 on a mismatch in OpenSSL 3.5 and exits 0 in the 3.0
# Ubuntu ships. Relying on the exit code accepted any certificate on
# exactly the distribution the nodes run.
#
# That makes the wording load-bearing, so pin it here: if a future
# OpenSSL rephrases this, the failure lands on this line rather than
# turning every certificate into an accepted one.
MATCH_OUT="$(openssl x509 -in "${FIXTURES}/good.crt" -noout -checkhost "$CN" 2>&1 || true)"
MISMATCH_OUT="$(openssl x509 -in "${FIXTURES}/wronghost.crt" -noout -checkhost "$CN" 2>&1 || true)"

if [[ "$MATCH_OUT" == *"does match"* && "$MATCH_OUT" != *"NOT match"* ]]; then
    ok "openssl still says 'does match' for a matching certificate"
else
    bad "openssl still says 'does match' for a matching certificate" "got: ${MATCH_OUT}"
fi
if [[ "$MISMATCH_OUT" == *"NOT match"* ]]; then
    ok "openssl still says 'NOT match' for a mismatched certificate"
else
    bad "openssl still says 'NOT match' for a mismatched certificate" "got: ${MISMATCH_OUT}"
fi

# ---------------------------------------------------------------------------
printf '\n=== Argument handling ===\n'
# ---------------------------------------------------------------------------
reset_scenario
RC=0; OUT="$(PATH="${FAKE_BIN}:${PATH}" "$ISSUE" --tls-dir "$TLS_DIR" 2>&1)" || RC=$?
if [[ $RC -ne 0 && "$OUT" == *"--common-name is required"* ]]; then
    ok "rejects a missing --common-name"
else
    bad "rejects a missing --common-name" "got ${RC}: ${OUT}"
fi

reset_scenario
run_issue --wat
assert_says "rejects unknown arguments" "Unknown argument"

# ---------------------------------------------------------------------------
printf '\n=== Renewal is a no-op until it needs to happen ===\n'
# ---------------------------------------------------------------------------
# A daily timer on three nodes that reissued every run would churn
# certificates constantly and SIGHUP the cluster for no reason.
reset_scenario
install_existing fresh
before="$(sha_of "${TLS_DIR}/vault.crt")"
run_issue --renew-within 1
assert_rc        "a fresh certificate means no work" 0
assert_log_lacks "no certificate is issued"          "/issue/"
assert_log_lacks "Vault is not signalled"            "systemctl"
assert_unchanged "the certificate on disk is untouched" "${TLS_DIR}/vault.crt" "$before"
assert_says      "and it says why"                   "nothing to do"

# The no-op path must not even authenticate — an hourly login per node
# for a no-op is pure token churn.
assert_log_lacks "it does not log in for a no-op" "approle/login"

reset_scenario
install_existing expiring
run_issue --renew-within 1
assert_rc      "a nearly expired certificate is renewed" 0
assert_log_has "a new certificate is issued"             "/issue/"

reset_scenario
install_existing fresh
run_issue --renew-within 1 --force
assert_rc      "--force renews regardless" 0
assert_log_has "and issues"                "/issue/"

# No certificate at all is the first-issue case, not an error.
reset_scenario
run_issue --renew-within 1
assert_rc      "a missing certificate is issued" 0
assert_log_has "and it issues one"               "/issue/"

# ---------------------------------------------------------------------------
printf '\n=== A bad certificate is never installed ===\n'
# ---------------------------------------------------------------------------
# Installing a mismatched pair and signalling Vault takes the listener
# down. On the active node that is an outage, caused by the thing meant
# to prevent one.
reset_scenario
install_existing fresh
before_crt="$(sha_of "${TLS_DIR}/vault.crt")"
before_key="$(sha_of "${TLS_DIR}/vault.key")"
export FAKE_ISSUE_MODE=mismatch
run_issue --force
assert_rc        "a mismatched cert/key pair aborts"  1
assert_says      "and says so"                        "do not match"
assert_unchanged "the old certificate survives"       "${TLS_DIR}/vault.crt" "$before_crt"
assert_unchanged "the old key survives"               "${TLS_DIR}/vault.key" "$before_key"
assert_log_lacks "Vault is not signalled"             "systemctl"

# A certificate for the wrong host installs cleanly and is then rejected
# by peers during the Raft join, with an error that reads like a network
# problem. Catch it here instead.
reset_scenario
install_existing fresh
before_crt="$(sha_of "${TLS_DIR}/vault.crt")"
export FAKE_ISSUE_MODE=wronghost
run_issue --force
assert_rc        "a certificate for another host aborts" 1
assert_says      "and names the host it wanted"          "$CN"
assert_unchanged "the old certificate survives"          "${TLS_DIR}/vault.crt" "$before_crt"
assert_log_lacks "Vault is not signalled"                "systemctl"

reset_scenario
install_existing fresh
before_crt="$(sha_of "${TLS_DIR}/vault.crt")"
export FAKE_ISSUE_MODE=empty
run_issue --force
assert_rc        "an empty certificate aborts"  1
assert_unchanged "the old certificate survives" "${TLS_DIR}/vault.crt" "$before_crt"

reset_scenario
export FAKE_ISSUE_MODE=nokey
run_issue --force
assert_rc   "a response with no private key aborts" 1
assert_says "and says what was missing"             "no certificate or no private key"

reset_scenario
export FAKE_ISSUE_MODE=notpem
run_issue --force
assert_rc "a non-PEM certificate aborts" 1

reset_scenario
install_existing fresh
before_crt="$(sha_of "${TLS_DIR}/vault.crt")"
export FAKE_ISSUE_RC=2
run_issue --force
assert_rc        "a refused issuance aborts"    1
assert_says      "and points at the likely cause" "allowed_domains"
assert_unchanged "the old certificate survives" "${TLS_DIR}/vault.crt" "$before_crt"

# ---------------------------------------------------------------------------
printf '\n=== The happy path installs and reloads ===\n'
# ---------------------------------------------------------------------------
reset_scenario
run_issue --force
assert_rc      "issuance succeeds" 0
if [[ -s "${TLS_DIR}/vault.crt" && -s "${TLS_DIR}/vault.key" && -s "${TLS_DIR}/ca.crt" ]]; then
    ok "certificate, key and CA are all written"
else
    bad "certificate, key and CA are all written"
fi

# The installed pair has to match, or the node stops serving.
cm="$(openssl x509 -noout -modulus -in "${TLS_DIR}/vault.crt" 2>/dev/null | openssl md5)"
km="$(openssl rsa -noout -modulus -in "${TLS_DIR}/vault.key" 2>/dev/null | openssl md5)"
if [[ -n "$cm" && "$cm" == "$km" ]]; then
    ok "the installed certificate and key match"
else
    bad "the installed certificate and key match"
fi

# The private key must not be world-readable. It is the one file here
# that grants the ability to impersonate this node.
if [[ "$PERMS_SUPPORTED" == true ]]; then
    PERM="$(stat -c '%a' "${TLS_DIR}/vault.key" 2>/dev/null || echo "unknown")"
    if [[ "$PERM" == "600" ]]; then
        ok "the private key is mode 0600"
    else
        bad "the private key is mode 0600" "got ${PERM}"
    fi
else
    skip "the private key is mode 0600" "this filesystem ignores chmod; runs in CI"
fi

assert_log_has "Vault is signalled to reload" "systemctl reload vault"

# Reload, not restart. A restart on the active node drops leadership and,
# without auto-unseal, needs a manual unseal to come back.
assert_log_lacks "it does not restart Vault" "restart vault"

reset_scenario
run_issue --force --no-reload
assert_rc        "--no-reload still installs" 0
assert_log_lacks "and does not signal"        "systemctl"
assert_says      "but warns the old cert is still live" "until reloaded"

# A failed reload is an error: the files on disk no longer match what the
# running process is serving, and nothing else will notice.
reset_scenario
export FAKE_RELOAD_RC=1
run_issue --force
assert_rc   "a failed reload is an error" 1
assert_says "and says what that means"    "still serving the previous certificate"

# ---------------------------------------------------------------------------
printf '\n=== The trust bundle is added to, not replaced ===\n'
# ---------------------------------------------------------------------------
# Nodes verify each other with tls_client_ca_file. Replacing the bundle
# with the PKI root mid-migration makes this node stop trusting every peer
# still on a bootstrap certificate — the cluster comes apart one node at a
# time as the rollout proceeds, which looks like a network fault.
reset_scenario
install_existing fresh
BOOTSTRAP_CA="$(cat "${TLS_DIR}/ca.crt")"
run_issue --force
NEW_BUNDLE="$(cat "${TLS_DIR}/ca.crt")"

if [[ "$NEW_BUNDLE" == *"$BOOTSTRAP_CA"* ]]; then
    ok "the bootstrap CA is still trusted after renewal"
else
    bad "the bootstrap CA is still trusted after renewal" "it was replaced"
fi

# Counting BEGIN lines: an appended bundle has more certificates than
# either input on its own.
BEFORE_N="$(grep -c 'BEGIN CERTIFICATE' <<< "$BOOTSTRAP_CA")"
AFTER_N="$(grep -c 'BEGIN CERTIFICATE' <<< "$NEW_BUNDLE")"
if [[ "$AFTER_N" -gt "$BEFORE_N" ]]; then
    ok "the issuing CA was added to the bundle"
else
    bad "the issuing CA was added to the bundle" "went from ${BEFORE_N} to ${AFTER_N} certificates"
fi

# Renewing repeatedly must not grow the bundle without bound — a daily
# timer would otherwise append the same certificate forever.
run_issue --force
REPEAT_N="$(grep -c 'BEGIN CERTIFICATE' "${TLS_DIR}/ca.crt")"
if [[ "$REPEAT_N" -eq "$AFTER_N" ]]; then
    ok "re-running does not append the same CA again"
else
    bad "re-running does not append the same CA again" "grew from ${AFTER_N} to ${REPEAT_N}"
fi

# --replace-ca is the deliberate way to drop the bootstrap CA, once every
# node is on PKI.
reset_scenario
install_existing fresh
BOOTSTRAP_CA="$(cat "${TLS_DIR}/ca.crt")"
run_issue --force --replace-ca
if [[ "$(cat "${TLS_DIR}/ca.crt")" != *"$BOOTSTRAP_CA"* ]]; then
    ok "--replace-ca drops what was there before"
else
    bad "--replace-ca drops what was there before"
fi

# ---------------------------------------------------------------------------
printf '\n=== Per-node certificate names ===\n'
# ---------------------------------------------------------------------------
# The local Docker profile serves /vault/tls/vault-0.crt, not vault.crt.
# Without --cert-name the script would write files Vault never reads, and
# report success.
reset_scenario
run_issue --force --cert-name vault-0
if [[ -s "${TLS_DIR}/vault-0.crt" && -s "${TLS_DIR}/vault-0.key" ]]; then
    ok "--cert-name controls the filenames written"
else
    bad "--cert-name controls the filenames written"
fi
if [[ ! -f "${TLS_DIR}/vault.crt" ]]; then
    ok "and the default name is not written as well"
else
    bad "and the default name is not written as well"
fi

# ---------------------------------------------------------------------------
printf '\n=== Reload verification is on unless disabled ===\n'
# ---------------------------------------------------------------------------
# A zero exit from the reload command means the signal was delivered, not
# that Vault accepted the certificate. Vault reports reload failures in
# its own log, asynchronously, and `systemctl reload` returns 0 anyway —
# so without a check the script reports success while the node keeps
# serving the old certificate until it expires.
#
# tests/integration found exactly that. What can be asserted here is that
# the guard is on by default and that the escape hatch is explicit.
ISSUE_TEXT="$(cat "$ISSUE")"
if [[ "$ISSUE_TEXT" == *"VERIFY_RELOAD=true"* ]]; then
    ok "reload verification defaults to on"
else
    bad "reload verification defaults to on"
fi
if [[ "$ISSUE_TEXT" == *"--no-verify-reload"* ]]; then
    ok "and there is an explicit way to skip it"
else
    bad "and there is an explicit way to skip it"
fi

# It compares the served certificate to the one just installed. Anything
# weaker — that the listener answers, say — would pass while Vault served
# the previous certificate.
if [[ "$ISSUE_TEXT" == *"WANT_SERIAL"* && "$ISSUE_TEXT" == *"SERVED_SERIAL"* ]]; then
    ok "it compares serials, not mere reachability"
else
    bad "it compares serials, not mere reachability"
fi

# ---------------------------------------------------------------------------
printf '\n=== Authentication ===\n'
# ---------------------------------------------------------------------------
reset_scenario
unset VAULT_TOKEN
run_issue --force
assert_rc   "no credentials is an error" 1
assert_says "and names what is missing"  "VAULT_ROLE_ID"

reset_scenario
unset VAULT_TOKEN
export VAULT_ROLE_ID=role VAULT_SECRET_ID=secret
run_issue --force
assert_rc      "AppRole is used when no token is set" 0
assert_log_has "it logs in"                           "approle/login"
assert_log_has "and revokes the token it minted"      "revoke"

reset_scenario
unset VAULT_TOKEN
export VAULT_ROLE_ID=role VAULT_SECRET_ID=secret FAKE_APPROLE_RC=2
run_issue --force
assert_rc        "a failed login aborts"   1
assert_log_lacks "and issues nothing"      "/issue/"

# A token the caller supplied belongs to the caller.
reset_scenario
run_issue --force
assert_log_lacks "a supplied VAULT_TOKEN is not revoked" "revoke"

# ---------------------------------------------------------------------------
printf '\n=== bootstrap-pki.sh ===\n'
# ---------------------------------------------------------------------------
reset_scenario
RC=0
OUT="$(FAKE_LOG="${WORK}/bootstrap.log" PATH="${FAKE_BIN}:${PATH}" \
    VAULT_ADDR='' VAULT_TOKEN=t "$BOOTSTRAP" 2>&1)" || RC=$?
if [[ $RC -ne 0 && "$OUT" == *"VAULT_ADDR"* ]]; then
    ok "bootstrap requires VAULT_ADDR"
else
    bad "bootstrap requires VAULT_ADDR" "got ${RC}: ${OUT}"
fi

RC=0
OUT="$(FAKE_LOG="${WORK}/bootstrap.log" PATH="${FAKE_BIN}:${PATH}" \
    VAULT_ADDR=https://x VAULT_TOKEN='' "$BOOTSTRAP" 2>&1)" || RC=$?
if [[ $RC -ne 0 && "$OUT" == *"VAULT_TOKEN"* ]]; then
    ok "bootstrap requires VAULT_TOKEN"
else
    bad "bootstrap requires VAULT_TOKEN" "got ${RC}: ${OUT}"
fi

# The PKI role must permit client auth as well as server auth. Raft peers
# authenticate in both directions, so a server-only role produces a
# cluster that serves clients and cannot form quorum.
BOOTSTRAP_TEXT="$(cat "$BOOTSTRAP")"
if [[ "$BOOTSTRAP_TEXT" == *"client_flag=true"* ]]; then
    ok "the node role allows client auth (Raft peers need it)"
else
    bad "the node role allows client auth (Raft peers need it)"
fi
if [[ "$BOOTSTRAP_TEXT" == *"allow_ip_sans=true"* ]]; then
    ok "the node role allows IP SANs (peers dial by address)"
else
    bad "the node role allows IP SANs (peers dial by address)"
fi

# The issuing policy must not grant more than issuance. A node that can
# rewrite the role can mint a certificate for any domain.
for forbidden in 'path "pki/root' 'sys/mounts' 'pki/roles'; do
    if [[ "$BOOTSTRAP_TEXT" == *"${forbidden}\""* ]]; then
        bad "the issuing policy does not grant ${forbidden}"
    else
        ok "the issuing policy does not grant ${forbidden}"
    fi
done

# ---------------------------------------------------------------------------
printf '\n=== The role does not overclaim ===\n'
# ---------------------------------------------------------------------------
# Vault PKI cannot issue the certificate the cluster needs in order to
# start. Every doc and default here has to say so, or someone will enable
# this expecting it to replace the bootstrap CA and find out during a
# rebuild that it does not.
DEFAULTS="${REPO_ROOT}/ansible/roles/vault_pki/defaults/main.yml"
TASKS="${REPO_ROOT}/ansible/roles/vault_pki/tasks/main.yml"

ENABLED="$(grep -E '^vault_pki_enabled:' "$DEFAULTS" | awk '{print $2}')"
if [[ "$ENABLED" == "false" ]]; then
    ok "the role is off by default"
else
    bad "the role is off by default" "got '${ENABLED}'"
fi

if grep -qi 'bootstrap' "$DEFAULTS" && grep -qi 'bootstrap' "$TASKS"; then
    ok "the role documents the bootstrap dependency"
else
    bad "the role documents the bootstrap dependency"
fi

# Renewing when there is nothing to renew means the bootstrap step was
# skipped. That has to fail loudly, not produce a timer that fails nightly.
if grep -q 'does not exist' "$TASKS"; then
    ok "the role fails clearly when there is no bootstrap certificate"
else
    bad "the role fails clearly when there is no bootstrap certificate"
fi

SERVICE="${REPO_ROOT}/ansible/roles/vault_pki/templates/vault-cert-renew.service.j2"
SERVICE_TEXT="$(cat "$SERVICE")"
if [[ "$SERVICE_TEXT" == *"EnvironmentFile="* ]]; then
    ok "credentials come from an EnvironmentFile, not the command line"
else
    bad "credentials come from an EnvironmentFile, not the command line"
fi
if [[ "$SERVICE_TEXT" != *"SECRET_ID="* && "$SERVICE_TEXT" != *"VAULT_TOKEN="* ]]; then
    ok "no credential is baked into the unit file"
else
    bad "no credential is baked into the unit file"
fi

# ---------------------------------------------------------------------------
printf '\n=== Bootstrap certificates for a cloud cluster ===\n'
# ---------------------------------------------------------------------------
# scripts/generate-cloud-certs.sh issues the TLS material the vault role
# copies to each node. It exists because on a cloud profile the inventory
# is dynamic and a host is named by its instance id, so the filenames are
# not knowable until after the apply.
#
# The assertions below are mostly about the SANs, because every way this
# goes wrong ends as a node serving TLS to nobody's satisfaction: a
# missing cluster servername forms no cluster while every node reports
# healthy, and a missing IP SAN fails the role's own delivery check.
GEN="${REPO_ROOT}/scripts/generate-cloud-certs.sh"
CERTS="${WORK}/cloud-certs"
INV_JSON="${WORK}/inventory.json"

cat > "$INV_JSON" <<'JSON'
{
  "_meta": {"hostvars": {
      "i-0aaa": {"private_ip_address": "10.0.1.10"},
      "i-0bbb": {"private_ip_address": "10.0.2.11"},
      "i-0nope": {}}},
  "vault_nodes": {"hosts": ["i-0aaa", "i-0bbb", "i-0nope"]}
}
JSON

GEN_RC=0
GEN_OUT="$("$GEN" --cluster-name vault-reference --hosts-json "$INV_JSON" \
    --out "$CERTS" --extra-san vault.example.com 2>&1)" || GEN_RC=$?

if [[ "$GEN_RC" == "0" ]]; then
    ok "it issues a CA and leaves from an inventory"
else
    bad "it issues a CA and leaves from an inventory" "exit ${GEN_RC}: ${GEN_OUT}"
fi

# Named by inventory hostname, because that is what the role looks for:
# vault_tls_cert_src ends files/tls/{{ inventory_hostname }}.crt.
if [[ -f "${CERTS}/i-0aaa.crt" && -f "${CERTS}/i-0aaa.key" \
   && -f "${CERTS}/i-0bbb.crt" && -f "${CERTS}/ca.crt" ]]; then
    ok "leaves are named by inventory hostname, beside a CA"
else
    bad "leaves are named by inventory hostname, beside a CA" \
        "got: $(find "$CERTS" -maxdepth 1 -type f -printf '%f ' 2>/dev/null)"
fi

# A host with no address would get a certificate the role then rejects,
# on the node, after the key had been written.
if [[ ! -f "${CERTS}/i-0nope.crt" ]]; then
    ok "a host with no private address is skipped, not half-issued"
else
    bad "a host with no private address is skipped, not half-issued" \
        "issued a certificate with no IP SAN to verify against"
fi

if openssl verify -CAfile "${CERTS}/ca.crt" "${CERTS}/i-0aaa.crt" >/dev/null 2>&1; then
    ok "each leaf verifies against the CA beside it"
else
    bad "each leaf verifies against the CA beside it"
fi

# Read the flag out of the role rather than hardcoding it here. This is
# the seam the whole section is for: the role demanded -checkhost against
# an IP, which no certificate anyone issues can satisfy, and a test that
# picked its own flag would have agreed with the generator and missed it.
ROLE_TASKS="${REPO_ROOT}/ansible/roles/vault/tasks/main.yml"
CHECK_FLAG="$(grep -oE '\-check(host|ip)' "$ROLE_TASKS" | head -1)"

if [[ -n "$CHECK_FLAG" ]]; then
    ok "the vault role states how it verifies a delivered certificate (${CHECK_FLAG})"
else
    bad "the vault role states how it verifies a delivered certificate" \
        "no -checkhost or -checkip in $(basename "$ROLE_TASKS") — this assertion reads nothing"
fi

DELIVERED="$(openssl x509 -in "${CERTS}/i-0aaa.crt" -noout "$CHECK_FLAG" 10.0.1.10 2>&1 || true)"
if [[ "$DELIVERED" == *"does match"* && "$DELIVERED" != *"NOT match"* ]]; then
    ok "and a correctly issued certificate passes that check"
else
    bad "and a correctly issued certificate passes that check" \
        "${CHECK_FLAG} 10.0.1.10 said: ${DELIVERED}"
fi

# The check is only worth having if it discriminates. Same flag, the
# other node's address.
WRONG="$(openssl x509 -in "${CERTS}/i-0aaa.crt" -noout "$CHECK_FLAG" 10.0.2.11 2>&1 || true)"
if [[ "$WRONG" == *"NOT match"* ]]; then
    ok "while another node's address fails it"
else
    bad "while another node's address fails it" \
        "${CHECK_FLAG} 10.0.2.11 said: ${WRONG}"
fi

# leader_tls_servername is the ONE name a follower verifies a leader
# against, whichever node that is. Without it on every leaf, no join
# succeeds and every node reports healthy on its own.
SERVERNAME="$(openssl x509 -in "${CERTS}/i-0bbb.crt" -noout \
    -checkhost vault-reference.vault.internal 2>&1 || true)"
if [[ "$SERVERNAME" == *"does match"* && "$SERVERNAME" != *"NOT match"* ]]; then
    ok "every leaf carries the cluster servername a follower verifies"
else
    bad "every leaf carries the cluster servername a follower verifies" "$SERVERNAME"
fi

# ---------------------------------------------------------------------------
printf '\n=== A certificate for a replacement node ===\n'
# ---------------------------------------------------------------------------
# An autoscaling group replaces a node without asking, and the replacement
# boots with nothing at /etc/vault.d/tls. The first real apply watched
# that happen: a terminated leader was replaced in 75 seconds by an
# instance whose Vault exited with `error loading TLS cert` until systemd
# stopped retrying, while the cluster carried on with two voters.
#
# The script kept the CA key for this case and had no mode that used it.
# Its only other option was --force, which mints a new CA -- reaching for
# that to fix one node is how a cluster stops forming. So: --add-missing
# signs one more leaf with the CA already trusted, and the assertions
# below are as much about what it leaves alone as what it writes.
ADD_JSON="${WORK}/inventory-plus-one.json"
sed 's/"vault_nodes": {"hosts": \["i-0aaa", "i-0bbb", "i-0nope"\]}/"vault_nodes": {"hosts": ["i-0aaa", "i-0bbb", "i-0nope", "i-0new"]}/; s/"i-0nope": {}/"i-0nope": {}, "i-0new": {"private_ip_address": "10.0.1.99"}/' \
    "$INV_JSON" > "$ADD_JSON"

if jq -e '.vault_nodes.hosts | index("i-0new")' "$ADD_JSON" >/dev/null 2>&1 \
   && jq -e '._meta.hostvars["i-0new"].private_ip_address' "$ADD_JSON" >/dev/null 2>&1; then
    ok "the replacement appears in the inventory the script reads"
else
    bad "the replacement appears in the inventory the script reads" \
        "the fixture edit produced no i-0new; every assertion below would be vacuous"
fi

BEFORE_ADD="$(cd "$CERTS" && sha256sum ./*.crt ./*.key | sort)"

ADD_RC=0
ADD_OUT="$("$GEN" --cluster-name vault-reference --hosts-json "$ADD_JSON" \
    --out "$CERTS" --add-missing 2>&1)" || ADD_RC=$?

if [[ "$ADD_RC" == "0" && -f "${CERTS}/i-0new.crt" && -f "${CERTS}/i-0new.key" ]]; then
    ok "--add-missing issues for the host that has no certificate"
else
    bad "--add-missing issues for the host that has no certificate" \
        "exit ${ADD_RC}: ${ADD_OUT}"
fi

# The whole point. A mode that rewrote the others would be --force with a
# gentler name: every node then needs material it has not been given.
AFTER_ADD="$(cd "$CERTS" && sha256sum ./*.crt ./*.key | sort | grep -v i-0new)"
if [[ "$AFTER_ADD" == "$BEFORE_ADD" ]]; then
    ok "and rewrites nothing that was already there, CA included"
else
    bad "and rewrites nothing that was already there, CA included" \
        "$(diff <(printf '%s\n' "$BEFORE_ADD") <(printf '%s\n' "$AFTER_ADD") | head -4)"
fi

if openssl verify -CAfile "${CERTS}/ca.crt" "${CERTS}/i-0new.crt" >/dev/null 2>&1; then
    ok "the new leaf verifies against the CA the running nodes already trust"
else
    bad "the new leaf verifies against the CA the running nodes already trust"
fi

NEW_SN="$(openssl x509 -in "${CERTS}/i-0new.crt" -noout \
    -checkhost vault-reference.vault.internal 2>&1 || true)"
if [[ "$NEW_SN" == *"does match"* && "$NEW_SN" != *"NOT match"* ]]; then
    ok "it carries the cluster servername, so it can join"
else
    bad "it carries the cluster servername, so it can join" "$NEW_SN"
fi

NEW_IP="$(openssl x509 -in "${CERTS}/i-0new.crt" -noout "$CHECK_FLAG" 10.0.1.99 2>&1 || true)"
if [[ "$NEW_IP" == *"does match"* && "$NEW_IP" != *"NOT match"* ]]; then
    ok "and its own address, so the role will deliver it"
else
    bad "and its own address, so the role will deliver it" "$NEW_IP"
fi

# Nobody passed --extra-san on this run. The load balancer's name was
# given once, on the first run, and a replacement without it fails for
# clients arriving through the load balancer and nowhere else -- which
# reads as that node being broken rather than as a missing SAN.
NEW_LB="$(openssl x509 -in "${CERTS}/i-0new.crt" -noout \
    -checkhost vault.example.com 2>&1 || true)"
if [[ "$NEW_LB" == *"does match"* && "$NEW_LB" != *"NOT match"* ]]; then
    ok "it inherits the extra SANs of the leaves beside it, unprompted"
else
    bad "it inherits the extra SANs of the leaves beside it, unprompted" \
        "vault.example.com: ${NEW_LB}"
fi

# Idempotent, because the operator running it does not know which hosts
# have material -- that is the question they are asking.
IDEM_STATE="$(cd "$CERTS" && sha256sum ./*.crt ./*.key | sort)"
IDEM_RC=0
IDEM_OUT="$("$GEN" --cluster-name vault-reference --hosts-json "$ADD_JSON" \
    --out "$CERTS" --add-missing 2>&1)" || IDEM_RC=$?
if [[ "$IDEM_RC" == "0" && "$IDEM_OUT" == *"Nothing to do"* \
   && "$(cd "$CERTS" && sha256sum ./*.crt ./*.key | sort)" == "$IDEM_STATE" ]]; then
    ok "a second run issues nothing and says so"
else
    bad "a second run issues nothing and says so" "exit ${IDEM_RC}: ${IDEM_OUT}"
fi

# A leaf's servername comes from --cluster-name. Signed against another
# cluster's CA it is a certificate for a name nobody verifies, delivered
# to a node that then joins nothing while reporting healthy.
WRONG_RC=0
WRONG_OUT="$("$GEN" --cluster-name other-cluster --hosts-json "$ADD_JSON" \
    --out "$CERTS" --add-missing 2>&1)" || WRONG_RC=$?
if [[ "$WRONG_RC" != "0" && "$WRONG_OUT" == *"is not other-cluster's"* ]]; then
    ok "it refuses a CA belonging to a different cluster"
else
    bad "it refuses a CA belonging to a different cluster" "exit ${WRONG_RC}: ${WRONG_OUT}"
fi

# With no CA there is nothing to add to, and the caller means a first run.
# Minting one silently would hand out material no node trusts.
NO_CA_RC=0
NO_CA_OUT="$("$GEN" --cluster-name vault-reference --hosts-json "$ADD_JSON" \
    --out "${WORK}/no-ca" --add-missing 2>&1)" || NO_CA_RC=$?
if [[ "$NO_CA_RC" != "0" && "$NO_CA_OUT" == *"ca.crt"* && ! -f "${WORK}/no-ca/ca.crt" ]]; then
    ok "and refuses to add to a directory with no CA in it"
else
    bad "and refuses to add to a directory with no CA in it" "exit ${NO_CA_RC}: ${NO_CA_OUT}"
fi

BOTH_RC=0
BOTH_OUT="$("$GEN" --cluster-name vault-reference --hosts-json "$ADD_JSON" \
    --out "$CERTS" --add-missing --force 2>&1)" || BOTH_RC=$?
if [[ "$BOTH_RC" != "0" && -f "${CERTS}/i-0aaa.crt" ]]; then
    ok "--add-missing with --force is refused rather than resolved"
else
    bad "--add-missing with --force is refused rather than resolved" \
        "exit ${BOTH_RC}: ${BOTH_OUT}"
fi

# The refusal a first-timer meets should name the mode that does what they
# want, or they reach for --force and replace the CA of a running cluster.
PLAIN_RC=0
PLAIN_OUT="$("$GEN" --cluster-name vault-reference --hosts-json "$ADD_JSON" \
    --out "$CERTS" 2>&1)" || PLAIN_RC=$?
if [[ "$PLAIN_RC" != "0" && "$PLAIN_OUT" == *"--add-missing"* ]]; then
    ok "a plain re-run still refuses, and points at --add-missing"
else
    bad "a plain re-run still refuses, and points at --add-missing" \
        "exit ${PLAIN_RC}: ${PLAIN_OUT}"
fi

SANS="$(openssl x509 -in "${CERTS}/i-0aaa.crt" -noout -ext subjectAltName 2>&1)"

if [[ "$SANS" == *"vault.example.com"* ]]; then
    ok "--extra-san reaches the certificate, for the load balancer's name"
else
    bad "--extra-san reaches the certificate" "$SANS"
fi

# serverAuth alone leaves Raft peers unable to authenticate to each other.
if openssl x509 -in "${CERTS}/i-0aaa.crt" -noout -text 2>/dev/null \
    | grep -q "TLS Web Client Authentication"; then
    ok "leaves are usable as a client too, which Raft peers must be"
else
    bad "leaves are usable as a client too, which Raft peers must be"
fi

if [[ "$(stat -c '%a' "${CERTS}/i-0aaa.key" 2>/dev/null)" == "600" ]]; then
    ok "private keys are not world-readable"
else
    bad "private keys are not world-readable" \
        "mode $(stat -c '%a' "${CERTS}/i-0aaa.key" 2>/dev/null)"
fi

# Re-running issues a new CA. Delivering it to some nodes and not others
# leaves a cluster that cannot form, so the second run has to be asked.
RERUN_RC=0
RERUN_OUT="$("$GEN" --cluster-name vault-reference --hosts-json "$INV_JSON" \
    --out "$CERTS" 2>&1)" || RERUN_RC=$?
if [[ "$RERUN_RC" != "0" && "$RERUN_OUT" == *"--force"* ]]; then
    ok "it refuses to replace existing material without --force"
else
    bad "it refuses to replace existing material without --force" \
        "exit ${RERUN_RC}: ${RERUN_OUT}"
fi

# An inventory with no usable hosts is the shape of "the cluster has not
# finished booting". Issuing a CA and no leaves would look like success.
EMPTY_JSON="${WORK}/empty-inventory.json"
printf '{"_meta": {"hostvars": {}}, "vault_nodes": {"hosts": []}}\n' > "$EMPTY_JSON"
EMPTY_RC=0
EMPTY_OUT="$("$GEN" --cluster-name vault-reference --hosts-json "$EMPTY_JSON" \
    --out "${WORK}/empty-certs" 2>&1)" || EMPTY_RC=$?
if [[ "$EMPTY_RC" != "0" && "$EMPTY_OUT" == *"private_ip_address"* ]]; then
    ok "an empty inventory is an error, not a CA with no leaves"
else
    bad "an empty inventory is an error, not a CA with no leaves" \
        "exit ${EMPTY_RC}: ${EMPTY_OUT}"
fi

# ---------------------------------------------------------------------------
printf '\n=== Results ===\n'
# ---------------------------------------------------------------------------
printf 'passed: %d\nfailed: %d\nskipped: %d\n' "$PASS" "$FAIL" "$SKIP"
if [[ $FAIL -gt 0 ]]; then
    red "FAILED"
    exit 1
fi
green "All ${PASS} assertions passed."
