#!/usr/bin/env bash
#
# generate-docs-index.sh — Build docs/README.md from the doc set
#
# Usage:
#   ./generate-docs-index.sh [--check]
#
# Options:
#   --check   Do not write anything. Exit 1 if docs/README.md differs
#             from what this script would generate, printing the diff.
#             This is what CI runs.
#
# WHAT THIS IS FOR
#
# Opening docs/ on GitHub renders a listing of filenames, which tells a
# reader that `audit.md` exists but not that it is the file explaining
# why two audit devices are the dangerous configuration. That gets worse
# with every document added.
#
# The index is generated rather than hand-maintained for the usual
# reason: a hand-maintained one silently stops covering each new
# document, and the omission is invisible to everyone except the person
# who needed that document. Each entry is the file's own H1 and its H2
# sections, so the index cannot describe a document as something it no
# longer is.
#
# Requirements: bash, awk, diff
#
# Nothing here reads the network or the cluster; it is a pure function of
# the files in docs/.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
DOCS_DIR="${REPO_ROOT}/docs"
INDEX="${DOCS_DIR}/README.md"

CHECK=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --check) CHECK=true; shift ;;
        -h|--help)
            printf 'Usage: %s [--check]\n' "$(basename "$0")"
            printf '  --check  fail if docs/README.md is stale, write nothing\n'
            exit 0
            ;;
        *)
            printf 'Unknown option: %s\n' "$1" >&2
            exit 2
            ;;
    esac
done

# Pull the H1 title and the H2 section names out of one document.
#
# Headings inside fenced code blocks are not headings — several docs open
# with a shell block whose comments would otherwise be read as sections —
# so the fence state is tracked rather than grepping for `^## `.
#
# Emits a single tab-separated line: title<TAB>section · section · ...
extract_headings() {
    awk '
        /^(```|~~~)/ { fence = !fence; next }
        fence        { next }
        !title && /^# / {
            sub(/^# +/, ""); title = $0; next
        }
        /^## / {
            sub(/^## +/, "")
            secs = secs (secs ? " · " : "") $0
        }
        END { printf "%s\t%s\n", title, secs }
    ' "$1"
}

# A literal pipe in a heading would end the table cell early.
escape_cell() {
    printf '%s' "${1//|/\\|}"
}

generate() {
    cat <<'HEADER'
<!--
  Generated by scripts/generate-docs-index.sh — run `make docs` to
  refresh. Editing this file by hand will be undone by the next run, and
  CI fails when it is stale.
-->

# Documentation

Every document in this directory, with the sections it contains. The
descriptions are each file's own headings rather than a summary written
alongside it, so an entry here cannot drift from the document it points
at.

Start with [deployment.md](deployment.md) to stand something up, or
[roadmap.md](roadmap.md) for what has been proven and what has only been
tested.

| Document | Sections |
|---|---|
HEADER

    local file name title sections
    # LC_ALL=C so the ordering does not depend on the contributor's locale.
    while IFS= read -r file; do
        name="$(basename "$file")"
        if [[ "$name" == "README.md" ]]; then
            continue
        fi

        IFS=$'\t' read -r title sections < <(extract_headings "$file")

        if [[ -z "$title" ]]; then
            printf 'ERROR: %s has no level-1 heading\n' "docs/$name" >&2
            return 1
        fi
        [[ -n "$sections" ]] || sections="—"

        printf '| [%s](%s) | %s |\n' \
            "$(escape_cell "$title")" "$name" "$(escape_cell "$sections")"
    done < <(LC_ALL=C find "$DOCS_DIR" -maxdepth 1 -name '*.md' | LC_ALL=C sort)
}

if [[ "$CHECK" == true ]]; then
    DIFF="$(mktemp)"
    trap 'rm -f "$DIFF"' EXIT

    # `diff` against the file rather than testing for its absence: a
    # missing index and a stale one are the same failure with the same
    # fix, and the diff says which it was.
    if diff -u --label 'expected (generated)' --label 'actual (committed)' \
        <(generate) "$INDEX" > "$DIFF" 2>&1; then
        printf 'docs/README.md is up to date.\n'
        exit 0
    fi

    printf 'docs/README.md is out of date. Run: make docs\n\n' >&2
    cat "$DIFF" >&2
    exit 1
fi

# Generated to a temporary file first: a document with no title aborts
# the run, and doing that to `> "$INDEX"` would leave the index truncated
# by the very failure it is meant to report.
OUT_TMP="$(mktemp)"
trap 'rm -f "$OUT_TMP"' EXIT

generate > "$OUT_TMP"
mv "$OUT_TMP" "$INDEX"
printf 'Wrote %s\n' "docs/README.md"
